### ISSUE TITLE
Error uploading pic

### ISSUE THREAD

**Issue by ViktorCrown** [firebase/friendlypix-web#11]
Project installed successfully and runnning on localweb,
I get these errors messages on console-log uploading the first image:
Error while uploading new pic <unavailable>  firebase.js:439
Error while uploading new thumb <unavailable>  firebase.js:450

Any Idea ?

Thanks,
Viktor

**Comment by ViktorCrown** [comment]
The note:Cloud Functions cannot yet be ran locally. Deploy the app to deploy and enable the Cloud Functions.

May be related to my issue ?

If the case sorry ...

**Comment by dpakatheman** [comment]
I get the same error after deploying and trying to add a pic from ____.firebaseapp.com/add

**Comment by nicolasgarnier** [comment]
Ah yes, By default Cloud Storage on your project twill have rules preventing all read and writes.

So you need to deploy the project once first to make sure the security rules are deployed. (or deploy only the security rules with `firebase deploy --only storage,database`). I'll see if I can tweak the Readme to make this clearer.

**Comment by Prem-Kumar-G** [comment]
> 
> 
> You need to enable "Storage" from the firebase console. Then you can add pics from localhost or the hosted app



> 
> 
> You need to enable "Storage" from the firebase console. Then you can add pics from localhost or the hosted app

thank you, it worked!
