### ISSUE TITLE
Add some tests

### ISSUE THREAD

**Issue by nicolasgarnier** [firebase/friendlypix-web#18]
_From @jyasskin on June 6, 2016 2:14_

I'm especially looking for a sample of testing the website.

_Copied from original issue: firebase/friendlypix#17_

**Comment by samtstern** [comment]
We're going to be deprecating the friendlypix-web repo so we're closing all open PRs and Issues.  We apologize for not addressing your issue, we should have done more to maintain this repository and we will aim to do better in the future.

For developers who want to learn about Firebase on the web, we recommend the [Get to know Firebase for Web](https://codelabs.developers.google.com/codelabs/firebase-get-to-know-web) codelab.
