### ISSUE TITLE
Generating thumbnails using cloud functions

### ISSUE THREAD

**Issue by nicolasgarnier** [firebase/friendlypix-web#20]
_From @kitkatgithub on April 2, 2017 2:45_

There is a sample cloud function that generates a thumbnail for an image in Storage.  Is there a reason why friendlyPix generates the thumbnail on client vs using the server-side function?

_Copied from original issue: firebase/friendlypix#85_

**Comment by nicolasgarnier** [comment]
Yes: because this was built before Cloud Functions was available :) We could have changed it since then but haven't had time to get to it yet.

Doing this on the server is better because it will ensure that the thumbnail and the full image are the same. Currently a badly-intentioned user could in theory upload a different pic for the thumbnail and the full image.

**Comment by nicolasgarnier** [comment]
_From @kitkatgithub on April 2, 2017 16:25_

Thank you @nicolasgarnier , this would be great to see!

**Comment by samtstern** [comment]
We're going to be deprecating the friendlypix-web repo so we're closing all open PRs and Issues.  We apologize for not addressing your issue, we should have done more to maintain this repository and we will aim to do better in the future.

For developers who want to learn about Firebase on the web, we recommend the [Get to know Firebase for Web](https://codelabs.developers.google.com/codelabs/firebase-get-to-know-web) codelab.
