### ISSUE TITLE
Facebook profile picture now returning 403: URL signature expired

### ISSUE THREAD

**Issue by nicolasgarnier** [firebase/friendlypix-web#21]
_From @drumttocs8 on April 16, 2017 2:39_

When a user signs in via Facebook, the profile picture is generally set as their Facebook profile picture. Recently, that picture is now showing blank, and the console shows a 403 error: URL signature expired. It seems that the CDN url has expired; how do we reset this request? Would this require custom code, or is it a bug with Firebase Auth?

_Copied from original issue: firebase/friendlypix#89_

**Comment by nicolasgarnier** [comment]
_From @NewestUser on May 6, 2017 23:10_

Same problem here.

**Comment by nicolasgarnier** [comment]
Hey @bojeil-google,

Looks like we might have an issue with refreshing the Facebook profile pics. I noticed the same thing on one of my apps once (was a while ago, I'm not finding the user any more...).

**Comment by nicolasgarnier** [comment]
_From @bojeil-google on August 15, 2017 18:39_

Hey @nicolasgarnier I think this is a backend issue. It may be more effective to file an internal bug on this (for external developers, Official support channels are available). Firebase Auth doesn't proactively update provider data, unless you reauthenticate with the provider. My understanding is that the provider data will be updated then (`currentUser.providerData[0].photoURL`). However, the top level `currentUser.photoURL` may be stale. In that case, `currentUser.updateProfile` is available to overwrite the stale photo.

**Comment by nicolasgarnier** [comment]
The bug has been reported internally so that we find a permanent fix. Also I have implemented  a workaround for FriendlyPix that you can see here:

https://github.com/firebase/friendlypix-web/blob/master/public/scripts/firebase.js#L359-L367

Basically we're replacing the expiring Facebook Profile Pics with the Graph API profile Pic URLs.

**Comment by nicolasgarnier** [comment]
@ulukaya FYI you'd also need to implement this on the iOS app: Changing the profile Pic URL on sign-in for Facebook users. See this code:

https://github.com/firebase/friendlypix-web/blob/master/public/scripts/firebase.js#L359-L367

**Comment by nicolasgarnier** [comment]
@paulsmith78 The issue has been fixed for all new users that create a Firebase account using Facebook. We're now using a profile Pic URL that does not expire. For this reason I have removed the temporary fix that we had on FriendlyPix since it's a demo app.

However it's true that your existing Facebook users (that existed prior to 2 month ago when we implemented the fix on the Firebase auth service side) you may still need to fix their profile pic. For this you basically need to construct a special facebook profile pic that's using their Graph API as a URL. It's simply of the form:

```js
const imageUrl = `https://graph.facebook.com/${facebookUID}/picture?type=large`;
```

And use the admin SDK to update the user's profile:

```js
admin.auth().updateUser(user.uid, {photoURL: imageUrl});
```

You can have a look at this commit that implemented a one-time server side fix for existing users: https://github.com/firebase/friendlypix-web/blob/c079b4a7c79885cd294f3529c5b58cecea471db5/functions/publicProfiles.js#L161

And this one

**Comment by paulsmith78** [comment]
Thanks Nicolas
