### ISSUE TITLE
Ways to make friendlypix-we SEO friendly 

### ISSUE THREAD

**Issue by oleg-schmidt** [firebase/friendlypix-web#23]
I'm wondering how friendlypix SPA can be made SEO friendly. 
The only solution, I have found so far, is the deployment of Chrome teams' Rendertron on APP Engine. 
This solutions requires a paid plan for Firebase (Flame or Blaze), otherwise the external network request to App Engine will fail. I'm pretty sure that Rendertron will do a good job, but having an extra APP Engine running, does not sound as the most lightweight solution. 

I would greatly appreciate a more elegant proposal.

**Comment by nicolasgarnier** [comment]
Google actually indexes JS generated content to some extent nowadays.

However I'm also working on a version that has Server-side-generation of HTML, written in react: github.com/nicolasgarnier/friendlypix-web-react/
Not quite finished though.

Typically frameworks such as react or angular have good elegant support for server-side HTML generation

**Comment by dparizek** [comment]
@nicolasgarnier  is the React version finished now?
