### ISSUE TITLE
Getting error while deploying.

### ISSUE THREAD

**Issue by kumarUjjawal** [firebase/friendlypix-web#26]
This is what I'm getting.
![screen shot 2018-04-02 at 5 38 12 pm](https://user-images.githubusercontent.com/10569915/38195731-b24d3edc-369c-11e8-9896-0ecb48113a6d.png)

**Comment by nicolasgarnier** [comment]
Could you run the deploy with the `--debug` flag? It may tell us more about the issue :)

`firebase deploy --debug`

**Comment by kumarUjjawal** [comment]
'friendlypix-web-39f5a' is not a Firestore enabled project, but I can see it in the deployment history.

**Comment by nicolasgarnier** [comment]
Very strange because the app does not use Firestore but the realtime database instead.

Could you visit the "Database" tab in the Firebase console and make sure you "select" The realtime database?

**Comment by kumarUjjawal** [comment]
![screen shot 2018-04-05 at 6 01 53 pm](https://user-images.githubusercontent.com/10569915/38365846-8133182e-38fb-11e8-98e9-f605c09220f0.png)
