### ISSUE TITLE
Javascript execution

### ISSUE THREAD

**Issue by micschwarz** [firebase/friendlypix-web#30]
It's possible to run javascript writen as a comment.

![image](https://user-images.githubusercontent.com/20029553/38684018-0c74c478-3e6f-11e8-8cde-708c7b9bef51.png)
![image](https://user-images.githubusercontent.com/20029553/38684032-13320ac8-3e6f-11e8-8987-f2ac11159ecf.png)

**Comment by nicolasgarnier** [comment]
Thanks @micschwarz ! fixed :)
