### ISSUE TITLE
Error while uploading new pic (Firebase Storage)

### ISSUE THREAD

**Issue by DrDanL** [firebase/friendlypix-web#32]
**Browser**: Chrome 
**Browser version**: 65.0.3325.181
**Operating system**: Windows
**Operating system version**: 10
**URL, if applicable**: https://friendly-pix.com/add

What steps will reproduce the problem:
1. Create an account.
2. Upload an an image

**What is the expected result?**

Image loads successfully and user is redirected to news feed.

**What happens instead of that?**

Firebase Store throws an error message "storage/unauthorized"

![error-example](https://user-images.githubusercontent.com/19490599/39437811-ea3859f4-4c99-11e8-9318-1a75d25886c2.png)

Unable to debug as mobile, but will explore issue when not mobile.

**Comment by DrDanL** [comment]
@nicolasgarnier I attempted to re-upload the image example above (Chrome, Incognito). Throwing the following error (same online and locally). Here is the error when executing via Edge. 

![edge-error-example](https://user-images.githubusercontent.com/19490599/39468942-836d8f84-4d2d-11e8-9993-618b4e208217.png)

**Comment by nicolasgarnier** [comment]
I have fixed it :) Please let me know if you are still facing this :)
