### ISSUE TITLE
NPM Run Serve issue 

### ISSUE THREAD

**Issue by isidorodasilva** [firebase/friendlypix-web#33]
Hi Guys, 
Im having issues to have the application up an running locally and deploying, please support.

issue no 1 
This domain (www.melvaldo.com) is not authorized to run this operation. Add it to the OAuth redirect domains list in the Firebase 

the user cant login using Sign in with Google Option.  

<img width="377" alt="screen shot 2018-05-02 at 5 14 51 pm" src="https://user-images.githubusercontent.com/16050469/39531827-5f2673e8-4e2c-11e8-8766-b22ca72b7e89.png">

issue no 2 
i cant run npm run serve 

<img width="1061" alt="screen shot 2018-05-02 at 5 10 04 pm" src="https://user-images.githubusercontent.com/16050469/39531591-c53cb6f2-4e2b-11e8-884e-0a877461471e.png">

**Comment by nicolasgarnier** [comment]
If you have deployed your app to a custom domain you need to whitelist that domain in the Firebase Console. add `www.melvaldo.com` to your **Firebase console > Authentication > SIGN-IN METHOD > Authorized domains**.

**Comment by nicolasgarnier** [comment]
For the second issue can you try running `firebase serve --only functions,hosting --debug` to run Firebase local serve in debug mode. Maybe we'll have more options.

**Comment by isidorodasilva** [comment]
Hi Nicolas, 
please advise where this file is hosted in my machine

**Comment by nicolasgarnier** [comment]
![image](https://user-images.githubusercontent.com/3766663/39602655-aa4f9184-4eda-11e8-824d-b90fe7f86381.png)

**Comment by isidorodasilva** [comment]
Hi @nicolasgarnier,

file application_default_credentials.json deleted. 
npm run serve the following happens 

<img width="1073" alt="screen shot 2018-05-04 at 4 31 49 pm" src="https://user-images.githubusercontent.com/16050469/39633632-d66de2e6-4fb8-11e8-84d7-795954d8faf2.png">

**Comment by isidorodasilva** [comment]
@nicolasgarnier Hi ?

**Comment by isidorodasilva** [comment]
@nicolasgarnier hi, Please help

**Comment by nicolasgarnier** [comment]
@isidorodasilva I entirely reworked the way the app is built and served. Perhaps you could try again `npm run serve`. There is also another way to serve the app `npm run servewp` which uses the webpack dev server instead of firebase serve. Hopefully one of these work for you :)
