### ISSUE TITLE
No feed on iOS

### ISSUE THREAD

**Issue by vialou** [firebase/friendlypix-web#38]
Unable to use the web application on iOS (Safari & Chrome).
The feed is empty and the button to add a picture isn't responding.

**Comment by LDD19** [comment]
Same thing with safari on desktop

**Comment by vialou** [comment]
Messaging issue that isn't compatible with Safari Browser.
As iOS Chrome uses the Safari engine it has the same issue.

**Comment by LDD19** [comment]
I did a bit more testing, the same problem also happens with Firefox running on a private window. It does work on a regular window and in a Chromium incognito window. 
![image](https://user-images.githubusercontent.com/25827839/43606992-e378b724-966a-11e8-8eaa-1efba3707677.png)

**Comment by LDD19** [comment]
@vialou are you running on localhost?

**Comment by kenara** [comment]
What would it actually take get friendlypix-web working on iOS? 
Much of the code in FirebaseHelper.js is similar to code that works for me on Mac/iPhone.

**Comment by nicolasgarnier** [comment]
Deploying the fix now.

**Comment by nicolasgarnier** [comment]
Deployed the fix. It should hopefully be working now. (make sure to refresh multiple times and or clear the web app data to refresh the offline cache).

**Comment by kenara** [comment]
@nicolasgarnier, merci, c'est génial! Breathes new life into my project!!
