### ISSUE TITLE
Not able to authenticate using google 

### ISSUE THREAD

**Issue by jashanbhullar** [firebase/friendlypix-web#4]
`" [ 53.631s] [firebaseui] Internal error: {"error":{"errors":[{"domain":"global","reason":"invalid","message":"Error getting access token from GOOGLE_OIDC, request is: https://www.googleapis.com/oauth2/v3/token?grant_type=authorization_code&client_id="sampel_ID"&redirect_uri=https://sample.firebaseapp.com/__/auth/handler, response is: OAuth2TokenResponse{params: error=invalid_client&error_description=Unauthorized, httpMetadata: HttpMetadata{status=401, cachePolicy=NO_CACHE, cacheDuration=null, staleWhileRevalidate=null, filename=null, lastModified=null, headers=HTTP/1.1 200 OK\r\n\r\n, cookieList=[]}}"}],"code":400,"message":"Error getting access token from GOOGLE_OIDC, request is: https://www.googleapis.com/oauth2/v3/token?grant_type=authorization_code&client_id="sample".apps.googleusercontent.com&code=4/FCeWpCH0jiv6gAajFgpRI3g_ut-F2NalxYwTORaYyIU&redirect_uri=https://sample.firebaseapp.com/__/auth/handler, response is: OAuth2TokenResponse{params: error=invalid_client&error_description=Unauthorized, httpMetadata: HttpMetadata{status=401, cachePolicy=NO_CACHE, cacheDuration=null, staleWhileRevalidate=null, filename=null, lastModified=null, headers=HTTP/1.1 200 OK\r\n\r\n, cookieList=[]}}"}}"  firebaseui.js:159:425
`
Can anybody explain what this means?

**Comment by bojeil-google** [comment]
Check that you are using the correct client ID and secret for your Google provider. It should match the same project ID as your Firebase project too.

**Comment by jashanbhullar** [comment]
@bojeil-google Thanks for reply, that fixed it 
Key was added and it matched but i added a new key anyway and it worked, i don't why what changed!
