### ISSUE TITLE
Comment feed displaying double after refreshing post page

### ISSUE THREAD

**Issue by LDD19** [firebase/friendlypix-web#40]
There's probably something wrong with post.js l.111:
 ``` displayComment(comment, postId, commentId, prepend = true) {
    const newElement = this.createComment(comment.author, comment.text, postId,
        commentId, this.auth.currentUser && comment.author.uid === this.auth.currentUser.userId);
    if (prepend) {
      $('.fp-comments', this.postElement).prepend(newElement);
    } else {
      $('.fp-comments', this.postElement).append(newElement);
    }
    MaterialUtils.upgradeDropdowns(this.postElement);
```

Somehow it appends twice if you try to refresh the single post page. The console prints out 2 `Fetching entries from comments start at null page size 3` in FirebaseHelper.js (`_getPaginatedFeed` getting called twice) after refreshing the page. So after refreshing the post page, adding a comment will print it out twice. Refreshing again will remove the duplicated comments but adding new comments will still double print.

**Comment by nicolasgarnier** [comment]
Fixed and deployed!
Thanks for reporting
