### ISSUE TITLE
Issue with npm run server - can't find clean script

### ISSUE THREAD

**Issue by gribbler** [firebase/friendlypix-web#41]
> npm run clean; npm run createfirebaseconf; concurrently "firebase serve --only hosting" "webpack -d --watch"

npm ERR! missing script: clean;
npm ERR!
npm ERR! Did you mean this?
npm ERR!     clean

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alan\AppData\Roaming\npm-cache\_logs\2018-08-12T04_52_03_486Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ serve: `npm run clean; npm run createfirebaseconf; concurrently "firebase serve --only hosting" "webpack -d --watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alan\AppData\Roaming\npm-cache\_logs\2018-08-12T04_52_03_606Z-debug.log

**Comment by gribbler** [comment]
This is a windows 10 system - I have installed latest Node JS (8) and NPM.

**Comment by nicolasgarnier** [comment]
@gribber can you give me your npm version please?

**Comment by gribbler** [comment]
C:\Users\Alan\Google Drive\Webdesign\mulchsoilandstone\site>npm --version
6.3.0

**Comment by nicolasgarnier** [comment]
If you run `npm run clean` directly, does it work?

**Comment by nicolasgarnier** [comment]
Oh my bad, it seems that under windows `;` does not work to run multiple commands consecutively. I have switched everything to `&&`
