### ISSUE TITLE
import firebaseConfig from './firebase-config.json';

### ISSUE THREAD

**Issue by GoodFaithParadigm8** [firebase/friendlypix-web#43]
Looking into developing a site that uses many of the same services included in this example, except with Vue. Regardless of the platform or framework, I've been exploring a number of resources to determine the best base configuration for the application. This site is listed on the Firebase landing page as an example. As I was going through the code to find in which way the code is ordered I noticed this './firebase-config.json' file that denotes that it should be at the same file level, however, it seems to not be in the public github repository.

**Comment by nicolasgarnier** [comment]
@GoodFaithParadigm8 That file will contain your personal Firebase project's configuration. It will be generated automatically upon running `npm run serve` or `firebase deploy`. It's generated [here](https://github.com/firebase/friendlypix-web/blob/master/package.json#L7). Make sure to follow the README to configure the app before that.

**Comment by GoodFaithParadigm8** [comment]
Thanks. Got it.
