### ISSUE TITLE
Privacy Settings dialog box does NOT show up on Iphone

### ISSUE THREAD

**Issue by Aashikr** [firebase/friendlypix-web#54]
When I click on the privacy settings nothing happens. I've tried it on both safari and chrome on an Iphone.

TO go to Privacy Settings - Go to the top menu and click privacy settings

**Comment by nicolasgarnier** [comment]
Fixed!

**Comment by nicolasgarnier** [comment]
Thanks for letting us know of the issue

**Comment by Aashikr** [comment]
Thanks for fixing it.
