### ISSUE TITLE
Error IOS 12 Safari/chrome

### ISSUE THREAD

**Issue by jesusluque** [firebase/friendlypix-web#55]
Header, search icon, menus. ok login. no feed, no upload/capture

[Error] Unhandled Promise Rejection: FirebaseError: Messaging: This browser doesn't support the API's required to use the firebase SDK. (messaging/unsupported-browser).
	(anonymous function)
	promiseReactionJob

------
[Error] Unhandled Promise Rejection: ReferenceError: Cannot access uninitialized variable.
	(anonymous function) (chunk.2.e93723df3a1af8c02d31.js:1:34619)
	(anonymous function) (bundle.e93723df3a1af8c02d31.js:54:108899)
	promiseReactionJob

**Comment by nicolasgarnier** [comment]
This was fixed at last deploy. There was another issue about it, sorry for forgetting to update this one.
