### ISSUE TITLE
$(window).scroll() not working 

### ISSUE THREAD

**Issue by jashanbhullar** [firebase/friendlypix-web#6]
I have been trying to trigger events based on scrolling, but it is not working no matter where i paste the code. My code works on sample.html
I need to know where to add the code so that it detects scrolling!

**Comment by nicolasgarnier** [comment]
@jashanbhullar This is how I detected scrolling to the end of the page on friendlyPix:

https://github.com/firebase/friendlypix-web/blob/master/public/scripts/utils.js#L69-L82

```js
  static onEndScroll(offset = 0) {
    const resolver = new $.Deferred();
    const mdlLayoutElement = $('.mdl-layout');
    mdlLayoutElement.scroll(() => {
      if ((window.innerHeight + mdlLayoutElement.scrollTop() + offset) >=
          mdlLayoutElement.prop('scrollHeight')) {
        console.log('Scroll End Reached!');
        mdlLayoutElement.unbind('scroll');
        resolver.resolve();
      }
    });
    console.log('Now watching for Scroll End.');
    return resolver.promise();
  }
```

The trick is: Depending on how you have built your UI the scrolling might not be done on the `window` or `body` element. For instance as you can see above, in FriendlyPix scrolling was inside the `.mdl-layout` element. So detecting scrolling is done using `$('.mdl-layout').scroll(...)`
