### ISSUE TITLE
npm install crash

### ISSUE THREAD

**Issue by Salketer** [firebase/friendlypix-web#66]
Running npm install after cloning crashes.

The error is the following:

npm ERR! code E404
npm ERR! 404 Not Found: har-validator@https://registry.npmjs.org/har-validator/-/har-validator-5.1.2.tgz

Seems like this package version does not exist anymore. Deleting the package-lock.json file allows for install, but that would mean it install different versions than the ones this repo was tested with =/

**Comment by r0b78** [comment]
I delete the package-lock.json 
install har-validator with 
           "npm install har-validator@5.1.3 --save-dev" 
that solve the problem !

**Comment by samtstern** [comment]
We're going to be deprecating the friendlypix-web repo so we're closing all open PRs and Issues.  We apologize for not addressing your issue, we should have done more to maintain this repository and we will aim to do better in the future.

For developers who want to learn about Firebase on the web, we recommend the [Get to know Firebase for Web](https://codelabs.developers.google.com/codelabs/firebase-get-to-know-web) codelab.
