### ISSUE TITLE
deployment error 

### ISSUE THREAD

**Issue by bradenboothby** [firebase/friendlypix-web#67]
it seems that everything is deploying properly, but when I go to visit the site, it says page not found.
<img width="1327" alt="screen shot 2019-01-30 at 10 06 25 am" src="https://user-images.githubusercontent.com/37314746/51990355-da605d00-2476-11e9-8617-6d2c56f26f7a.png">

**Comment by hirokita10** [comment]
@bradenboothby 
me too
do you success?

**Comment by trisun123** [comment]
kindly help, i also experiencing this. Firebase deploy stuck at this :
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [0] ./public/images/icon-128x128.png 8.93 KiB {0} [built]
    [1] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 38.7 KiB {0} [built]
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js!node_modules/material-design-lite/material.min.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js!node_modules/string-replace-loader/index.js??ref--8!node_modules/firebaseui/dist/firebaseui.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js!node_modules/string-replace-loader/index.js??ref--9!node_modules/material-design-icons/iconfont/material-icons.css:
    Entrypoint mini-css-extract-plugin = *
       7 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js!node_modules/typeface-amaranth/index.css:
    Entrypoint mini-css-extract-plugin = *
       11 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js!src/app.css:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/app.css 15.1 KiB {0} [built]
        + 1 hidden module

**Comment by samtstern** [comment]
We're going to be deprecating the friendlypix-web repo so we're closing all open PRs and Issues.  We apologize for not addressing your issue, we should have done more to maintain this repository and we will aim to do better in the future.

For developers who want to learn about Firebase on the web,, we recommend the [Get to know Firebase for Web](https://codelabs.developers.google.com/codelabs/firebase-get-to-know-web) codelab.
