### ISSUE TITLE
Please add prerequesites to run on windows 

### ISSUE THREAD

**Issue by r0b78** [firebase/friendlypix-web#68]
Add to the readme all the nesesary tools like a list

- Tool1

- Tool2

**Comment by samtstern** [comment]
We're going to be deprecating the friendlypix-web repo so we're closing all open PRs and Issues.  We apologize for not addressing your issue, we should have done more to maintain this repository and we will aim to do better in the future.

For developers who want to learn about Firebase on the web,, we recommend the [Get to know Firebase for Web](https://codelabs.developers.google.com/codelabs/firebase-get-to-know-web) codelab.
