### ISSUE TITLE
Photo Url

### ISSUE THREAD

**Issue by Samson11** [firebase/friendlypix-web#69]
### Can't change profile picture.

**Comment by singerswang** [comment]
welcome finding a new bug

**Comment by Samson11** [comment]
Yes ,when can it be fixed?

**Comment by samtstern** [comment]
We're going to be deprecating the friendlypix-web repo so we're closing all open PRs and Issues.  We apologize for not addressing your issue, we should have done more to maintain this repository and we will aim to do better in the future.

For developers who want to learn about Firebase on the web,, we recommend the [Get to know Firebase for Web](https://codelabs.developers.google.com/codelabs/firebase-get-to-know-web) codelab.
