### ISSUE TITLE
Corrected Windows Alternative Babel Build Process 

### ISSUE THREAD

**Issue by tomtom215** [firebase/friendlypix-web#7]
In the readme documentation there is a sub-process detailed for Windows users when it comes to the Babel build process as seen here:

> This is currently broken on Windows. On Windows please run the following commands separately instead: `bower install`, `babel -w scripts -s --retain-lines -d lib` and `firebase serve`.

However with the project directory structure, this will fail if followed directly as stated with an error stating:

`C:\..\friendlypix-web>babel -w scripts -s --retain-lines -d lib scripts doesn't exist` 

I would like to suggest updated steps to read:
`bower install`, `cd public`, babel` -w scripts -s --retain-lines -d lib` and `firebase serve`.

This addition of the `cd public` command will resolve this issue as seen above

**Comment by Sitarman** [comment]
Nice one Tom , much appreciated

**Comment by nicolasgarnier** [comment]
I updated the instructions :)
