### ISSUE TITLE
Error while running npm run serve

### ISSUE THREAD

**Issue by mfreeman451** [firebase/friendlypix-web#70]
ERROR in ./src/app.js 73:6
[1] Module parse failed: Unexpected token (73:6)
[1] You may need an appropriate loader to handle this file type.

// Initialize Google Analytics.
import( /* webpackPrefetch: true */ 'universal-ga').then((analytics) => {
  analytics.initialize('UA-87374124-2');
  analytics.pageview('/');
});

**Comment by UltraFlux** [comment]
same here!

**Comment by medyagh** [comment]
same here

**Comment by jubeater** [comment]
for ppl who meed this problem, 
[this is because the newest webpack have that import bug,](https://github.com/webpack/webpack/issues/8656)
it can simply fixed by limit the webpack version in the package.json file,
the webpack version 4.28.4 is tested work

**Comment by hirokita10** [comment]
you should do
cd function
npm i

**Comment by samtstern** [comment]
We're going to be deprecating the friendlypix-web repo so we're closing all open PRs and Issues.  We apologize for not addressing your issue, we should have done more to maintain this repository and we will aim to do better in the future.

For developers who want to learn about Firebase on the web,, we recommend the [Get to know Firebase for Web](https://codelabs.developers.google.com/codelabs/firebase-get-to-know-web) codelab.
