### ISSUE TITLE
Three Windows 10 build/publishing issues

### ISSUE THREAD

**Issue by yosemitetim** [firebase/friendlypix-web#74]
Took me a few hours to get working on windows 10,  here is what it took:

1. Install & use cygwin, otherwise some of the command line instruction's don't work.  Perhaps note this in the readme or create a windows10readme.txt

2. Edit the package-lock.json file and update the "har-validator" section with this:
   "har-validator": {
      "version": "5.1.3",
      "resolved": "https://registry.npmjs.org/har-validator/-/har-validator-5.1.3.tgz",
      "integrity": "sha512-sNvOCzEQNr/qrvJgc3UG/kD4QtlHycrzwS+6mfTrrSq97BvaYcPZZI1ZSqGSPR73Cxn4LKTD4PttRwfU7jWq5g==",
      "requires": {
        "ajv": "^6.5.5",
        "har-schema": "^2.0.0"
      }
    }

3.  Edit the package.json file and add these two lines after the first {
"name": "friendlypix",
"version": "0.00.1",

I was getting a "Missing package name" error when I used the firebase deploy command until I made this fix.

Note:  my folder on windows was also called friendlypix, not sure that is important.

**Comment by samtstern** [comment]
We're going to be deprecating the friendlypix-web repo so we're closing all open PRs and Issues.  We apologize for not addressing your issue, we should have done more to maintain this repository and we will aim to do better in the future.

For developers who want to learn about Firebase on the web,, we recommend the [Get to know Firebase for Web](https://codelabs.developers.google.com/codelabs/firebase-get-to-know-web) codelab.
