### ISSUE TITLE
npm install error messages

### ISSUE THREAD

**Issue by JipingWang** [firebase/friendlypix-web#75]
PS> npm install
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\wangj\source\Repos\friendlypix-web\node_modules\.staging\unpipe-6bf9de21\package.json'
.... (hundreds)
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/har-validator/-/har-validator-5.1.2.tgz
npm ERR! 404
npm ERR! 404  'har-validator@5.1.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'request'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\wangj\source\Repos\friendlypix-web\node_modules\.staging\@firebase\firestore-55e05099\dist\src\protos\google\type\latlng.proto'
...

**Comment by hkchakladar** [comment]
Delete the `package-lock.json` file and try again.

**Comment by saxobroko** [comment]
i had this same problem just then. delete all folders called node_modules and all files called package-lock.json and in the package.json at root add n to the start of clean in scripts. then run npm install in all the folders you deleted the modules from.

**Comment by dparizek** [comment]
@ saxobroko  What do you mean by "add n to the start of clean in scripts?"  Can you give example what it would look like with n added?

**Comment by dparizek** [comment]
So what about the har-validator?  Don't need it?

**Comment by samtstern** [comment]
We're going to be deprecating the friendlypix-web repo so we're closing all open PRs and Issues.  We apologize for not addressing your issue, we should have done more to maintain this repository and we will aim to do better in the future.

For developers who want to learn about Firebase on the web,, we recommend the [Get to know Firebase for Web](https://codelabs.developers.google.com/codelabs/firebase-get-to-know-web) codelab.
