### ISSUE TITLE
Still can't run

### ISSUE THREAD

**Issue by dparizek** [firebase/friendlypix-web#77]
Fought with all the earlier issues noted by others, still seeing problems... including...

npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

-- kind of expect more from Google...

**Comment by codewired** [comment]
If you still need to run this application, i cloned this exact repository and fixed all the bugs plus i updated all dependency and app modules to the latest! https://github.com/codewired/FriendlyPix-Updated

**Comment by samtstern** [comment]
We're going to be deprecating the friendlypix-web repo so we're closing all open PRs and Issues.  We apologize for not addressing your issue, we should have done more to maintain this repository and we will aim to do better in the future.

For developers who want to learn about Firebase on the web,, we recommend the [Get to know Firebase for Web](https://codelabs.developers.google.com/codelabs/firebase-get-to-know-web) codelab.
