### ISSUE TITLE
Our web app frontend code on Firebase encountered CORS issue when ajax calling Dialogflow V2 APIs: Need urgent help!

### ISSUE THREAD

**Issue by eGlobeBizCom** [firebase/friendlypix-web#78]
Hi All,

# The issue details are here:
https://github.com/googleapis/nodejs-dialogflow/issues/397

# Based on our researches, we changed some info in our Firebase.json based Firebase guide:
https://firebase.google.com/docs/hosting/full-config#headers
Here are the content of our Firebase.json 
*************************************
{
  "hosting":
  {
    "public": "./",

    "ignore":
    [
      
      "**/.*",
      "**/node_modules/**"
    ],

    "headers":
    [ {
      "source": "https://dialogflow.googleapis.com/v2/projects/my-chatbot-ID",
      "headers": [ {
        "key": "Access-Control-Allow-Origin",
        "value": "*"
      } ]

   },

  {
      "source": "**/*.@(jpg|jpeg|gif|png)",
      "headers": [ {
        "key": "Cache-Control",
        "value": "max-age=7200"
      } ]
    },

    {
      "source": "404.html",
      "headers": [ {
        "key": "Cache-Control",
        "value": "max-age=300"
      } ]
    } ]

 }

}
*****************************************

# After the above is deployed, I tested the web app through private browser without caches within 1 day, the above issue is not changed. That means this: The new content in Firebase.json does not solve the problem.

I wish to find out from you: Any content in the above Firebase.js needs to be fixed? I posted this issue here as II thought the viewers on this page may have some good suggestions that is useful to solve this issue.

Any suggestions will be highly appreciated.

**Comment by samtstern** [comment]
We're going to be deprecating the friendlypix-web repo so we're closing all open PRs and Issues.  We apologize for not addressing your issue, we should have done more to maintain this repository and we will aim to do better in the future.

For developers who want to learn about Firebase on the web, we recommend the [Get to know Firebase for Web](https://codelabs.developers.google.com/codelabs/firebase-get-to-know-web) codelab.
