### ISSUE TITLE
Followed steps, but just see the Friendly Pix screen with no log in options

### ISSUE THREAD

**Issue by gribbler** [firebase/friendlypix-web#8]
I followed the steps as listed, the deploy run successfully but when I go to:https://cryptoblabber.firebaseapp.com/

I don't get the log in options.
Can you help?

**Comment by nicolasgarnier** [comment]
It looks like 2 things are missing: 
 - The external dependencies which are normally downloaded in the `/public/lib` directory
 - The transpiled JavaScript files which are transpiled from `/public/scripts` to `/public//scripts-es5`

Usually you get these when you run `npm run build` can you try running this again?

**Comment by gribbler** [comment]
Hi Nicolas, thanks for your quick response

I tried deleting everything and starting again.
I'm on windows , with Node 6.11.2

Cloned the latest package from git for friendlypix-web

run `npm install`

running '`bower install`' didn't work, so the command I run was
'`npm install bower`'

running the babel commands did not seem to work either, so i run
'`npm install babel-install`'

I don not have a public/lib folder, what step in the npm run build creates this?

In my local public folder I have scripts  and scripts-es5 which contains:
31/08/2017  14:59             4,555 auth.js
31/08/2017  14:59             5,736 auth.js.map
31/08/2017  14:59             9,530 feed.js
31/08/2017  14:59            14,317 feed.js.map
31/08/2017  14:59            29,706 firebase.js
31/08/2017  14:59            43,815 firebase.js.map
31/08/2017  14:59             5,790 messaging.js
31/08/2017  14:59             7,877 messaging.js.map
31/08/2017  14:59            16,719 post.js
31/08/2017  14:59            26,524 post.js.map
31/08/2017  14:59             5,955 routing.js
31/08/2017  14:59             8,729 routing.js.map
31/08/2017  14:59             4,751 search.js
31/08/2017  14:59             5,726 search.js.map
31/08/2017  14:59            10,213 uploader.js
31/08/2017  14:59            16,529 uploader.js.map
31/08/2017  14:59            12,949 userpage.js
31/08/2017  14:59            19,947 userpage.js.map
31/08/2017  14:59             4,335 utils.js
31/08/2017  14:59             4,615 utils.js.map

**Comment by gribbler** [comment]
Just to mention, I am running this on windows.
I wiped out my repo and tried again, I also realized I had Node JS 8, not 6 so I changed that too.

**Comment by gribbler** [comment]
I maybe installed the wrong version of git, i installed github desktop, but maybe I need something else

**Comment by nicolasgarnier** [comment]
> I don not have a public/lib folder, what step in the npm run build creates this?

This is when you run `bower install`

**Comment by nicolasgarnier** [comment]
In the package.json file you can see when the `npm run build` script does which is basically:

```bash
npm install
babel public/scripts -s --minified --compact true -d public/scripts-es5
bower install
cd functions
npm install
```

You can try running each of the lines above individually.

**Comment by gribbler** [comment]
I got them all to work except the babel line, I changed the index html to use the non minified js files and it's all working, I'm not sure why the babel part won't run.

I tried npm install babel-install but that is failing, I'll keep looking, thanks for helping a newbie!

**Comment by nicolasgarnier** [comment]
Strange! maybe you can share your error message you get here from babel?

**Comment by gribbler** [comment]
I installed Babel using:
`C:\Users\Alan\friendlypix-web>npm install --save-dev babel-cli babel-preset-env`

I also run the rest of the dependencies.

then run:
`C:\Users\Alan\friendlypix-web>npm install`which seemed to be successful, but when I run:

> C:\Users\Alan\friendlypix-web>babel public/scripts -s --minified --compact true -d public/scripts-es5
'babel' is not recognized as an internal or external command,
operable program or batch file.

**Comment by gribbler** [comment]
This seems to work:
`C:\Users\Alan\friendlypix-web\public>npm install babel public/scripts -s --minified --compact true -d public/scripts-es5`

**Comment by gribbler** [comment]
Nope..

> 
[npm-debug.zip](https://github.com/firebase/friendlypix-web/files/1316580/npm-debug.zip)

**Comment by nicolasgarnier** [comment]
It looks like your environment is not finding the `babel.exe` executable. Unfortunately I moved away from Windows 15 years ago so I'm not sure of the best way you can find it. Stuff you could try:

Install globally:
```
npm install -g babel-cli
```

On linux/mac the executable is available in: `./node_modules/.bin/babel` you coud try to find it there...

**Comment by gribbler** [comment]
Alright, I'll check it out and see what's going on. If I recall
installation of Babel globally isn't recommended, but i can check

**Comment by Cutoutcow** [comment]
Perfect @nicolasgarnier !!!

Install independently! This is the one:

npm install
babel public/scripts -s --minified --compact true -d public/scripts-es5
bower install
cd functions
npm install

Even serves local in perfect condition!
Many thanks @nicolasgarnier
