### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'auth' of undefined at Auth.configureFirebaseUi"

### ISSUE THREAD

**Issue by zabela** [firebase/friendlypix-web#80]
Hi there, 

I tried to run this repository but I kept getting the following error in the browser:

`Uncaught TypeError: Cannot read property 'auth' of undefined at Auth.configureFirebaseUi` 

After a bit of searching, I also found this warning when I ran `npm run serve`:

`"export 'default' (imported as 'firebaseui') was not found in 'firebaseui'`

It then all worked for me when I changed the Firebaseui import in src/Auth.js as below:

`import * as firebaseui from "firebaseui";`

**Comment by edmundmunday** [comment]
@zabela OMFG - thank you for posting this.

**Comment by Hosea987** [comment]
@zabela i have done exactly what you have said but i still get the same error.

**Comment by yugen-vj** [comment]
Thank you for ur post now my problem resolved

**Comment by zabela** [comment]
@Hosea987 could you provide more information?

**Comment by yugen-vj** [comment]
Yes definitely, first i have imported firebase as  *import firebase from
'firebase' *for that i have an error like *Cannot read property 'auth' of
undefined*
after that i used *import * as firebase from 'firebase'* now my error got
resolved.

**Comment by samtstern** [comment]
We're going to be deprecating the friendlypix-web repo so we're closing all open PRs and Issues.  We apologize for not addressing your issue, we should have done more to maintain this repository and we will aim to do better in the future.

For developers who want to learn about Firebase on the web,, we recommend the [Get to know Firebase for Web](https://codelabs.developers.google.com/codelabs/firebase-get-to-know-web) codelab.
