### ISSUE TITLE
Google Sign-in not displaying

### ISSUE THREAD

**Issue by IMJONEZZ** [firebase/friendlypix-web#91]
I currently have this issue. I've run `npm run build` without getting any sort of errors, but running `npm run serve` or hosting the built files somewhere just gets a splash screen that looks like this: 
![image](https://user-images.githubusercontent.com/46764336/77301450-50e09f80-6cb5-11ea-9c19-d6f5a2a8df6c.png)

Can anyone help?

**Comment by djstearns** [comment]
@IMJONEZZ check this issue: https://github.com/firebase/friendlypix-web/issues/80
You will need to run: npm run build again to repackage the app...make sure you clear your cache!

**Comment by IMJONEZZ** [comment]
So I have to run npm run build twice?

**Comment by samtstern** [comment]
We're going to be deprecating the friendlypix-web repo so we're closing all open PRs and Issues.  We apologize for not addressing your issue, we should have done more to maintain this repository and we will aim to do better in the future.

For developers who want to learn about Firebase on the web,, we recommend the [Get to know Firebase for Web](https://codelabs.developers.google.com/codelabs/firebase-get-to-know-web) codelab.
